# Generated by Django 4.0.6 on 2022-11-26 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_alter_order_order_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='naprcrm',
            name='description',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='naprcrm',
            name='image',
            field=models.ImageField(null=True, upload_to='napr/'),
        ),
    ]
