# Generated by Django 4.0.6 on 2022-11-27 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_naprcrm_description_naprcrm_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_name',
            field=models.CharField(max_length=30, verbose_name='Имя'),
        ),
    ]
